#!/usr/bin/env node
/**
 * Copies the compiled ClashArena ABI out of the Foundry artifacts and into `lib/abi/`, so the
 * frontend can never drift from the deployed contract. Run after `forge build`.
 *
 *   node scripts/sync-abi.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const artifact = join(root, "contracts/out/ClashArena.sol/ClashArena.json");
const target = join(root, "lib/abi/clashArena.ts");

let parsed;
try {
  parsed = JSON.parse(readFileSync(artifact, "utf8"));
} catch {
  console.error(`Could not read ${artifact}. Run \`forge build\` in contracts/ first.`);
  process.exit(1);
}

const banner = `// Generated by scripts/sync-abi.mjs from contracts/out/ClashArena.sol/ClashArena.json.
// Do not edit by hand — run \`npm run sync:abi\` after changing the contract.
`;

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, `${banner}\nexport const clashArenaAbi = ${JSON.stringify(parsed.abi, null, 2)} as const;\n`);

console.log(`Wrote ${parsed.abi.length} ABI entries to lib/abi/clashArena.ts`);
